site_name: napari-layer-table
site_description: A plugin to display a layer as a table.
site_author: Cudmore Lab

theme: material

repo_url: https://github.com/mapmanager/napari-layer-table

plugins:
  #- mkdocs-jupyter
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - src
      handlers:
        python:
          selection:
            inherited_members: false
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_category_heading: true
            group_by_category: false
            heading_level: 1
            merge_init_into_class: true
            show_signature_annotations: true
            #show_object_full_path: true

nav:
- Home: index.md
- Scripting: scripting.md
- API:
    - Overview: api/overview.md
    - _my_widget: api/_my_widget.md
    - _table_widget: api/_table_widget.md
    - _data_model: api/_data_model.md
