site_name: napari-layer-table
site_description: A plugin to display a layer as a table.
site_author: Cudmore Lab

theme: material

repo_url: https://github.com/mapmanager/napari-layer-table

plugins:
  #- mkdocs-jupyter
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - src
      handlers:
        python:
          selection:
            inherited_members: false
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_category_heading: true
            group_by_category: false
            heading_level: 2
            #show_object_full_path: true

# ERROR    -  Config value: 'pages'. Error: The configuration option 'pages' was
# removed from MkDocs. Use 'nav' instead.
#pages:
nav:
- Home: overview.md
- Scripting: scripting.md
- API:
    - napari_layer_table: api/napari_layer_table.md
